name: flutter_feed
description: Video Feed

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hooks_riverpod: 2.0.0-dev.8
  assorted_layout_widgets: 6.0.0
  gap: 2.0.0
  cached_network_image: 3.2.1
  flutter_hooks: 0.18.4
  auto_route: 4.0.1
  freezed_annotation: 2.0.3

  dartx: 1.1.0
  flutter_svg: 1.0.3
  intl: 0.17.0
  json_annotation: 4.5.0
  widgetbook: 2.2.1
  animated_size_and_fade: 3.0.0
  font_awesome_flutter: 10.1.0

  #Network
  dio: 4.0.6
  dio_smart_retry: 1.2.0
  dio_logger: ^4.0.0+6

  video_player: 2.4.2
  queue: 3.1.0+1
  visibility_detector: 0.3.3
  mime: 1.0.2
  video_thumbnail: 0.5.0
  shimmer: ^2.0.0

  uuid: 3.0.6

  package_info: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1
  flutter_launcher_icons: 0.9.2
  build_runner: 2.1.10
  freezed: 2.0.3+1
  json_serializable: 6.2.0
  auto_route_generator: 4.0.0
  flutter_gen_runner: 4.1.6
  intl_utils: 2.6.1
  test: 1.21.1

dependency_overrides:
  freezed: 2.0.3+1
  freezed_annotation: 2.0.3
  analyzer: 3.4.1
  dart_style: 2.2.3
  built_value_generator: 8.3.0
  visibility_detector: 0.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/svgs/
    - assets/images/

  fonts:
    - family: TTCommons
      fonts:
        - asset: assets/fonts/TT_Commons_Regular.otf
          weight: 400
        - asset: assets/fonts/TT_Commons_DemiBold.otf
          weight: 600
        - asset: assets/fonts/TT_Commons_Bold.otf
          weight: 700
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_Bold.otf
          weight: 700

flutter_gen:
  output: lib/resources/
  line_length: 120
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
